"""Shared data paths for all reproduction scripts.

The data/ directory contains either:
  - Pre-computed artifacts downloaded from Zenodo
  - Outputs generated by the pipeline (steps 1-4)

The images/ directory is only needed for steps 1-2 (feature extraction).
"""

from __future__ import annotations

from pathlib import Path

DATA_DIR = Path("data")

# --- Input: images (only needed for feature extraction) ---
CONTEMPART_IMAGES_DIR = DATA_DIR / "contempart_images"
WIKIART_IMAGES_DIR = DATA_DIR / "wikiart_images"

# --- Input: metadata ---
MANIFEST_PATH = DATA_DIR / "images_manifest.csv"
ARTIST_META_PATH = DATA_DIR / "artists.csv"
SMALL_GRAPH_PATH = DATA_DIR / "graph_gu_node2vec.csv"
WIKIART_META_PATH = DATA_DIR / "wikiart_metadata.csv"
EDGELIST_PATH = DATA_DIR / "edgelist.csv"

# --- Output: embeddings ---
EMBEDDINGS_DIR = DATA_DIR / "embeddings"
VGG_EMB_PATH = EMBEDDINGS_DIR / "vgg_fc7.npy"
TEXTURE_EMB_PATH = EMBEDDINGS_DIR / "texture_gram_svd.npy"
ARCHETYPE_PATH = EMBEDDINGS_DIR / "archetype_m36.npy"
WIKIART_VGG_PATH = EMBEDDINGS_DIR / "wikiart_vgg_fc7.npy"
WIKIART_TEXTURE_PATH = EMBEDDINGS_DIR / "wikiart_texture_gram_svd.npy"
WIKIART_ARCHETYPE_PATH = EMBEDDINGS_DIR / "wikiart_archetype_m35.npy"

# --- Output: distances ---
DISTANCES_DIR = DATA_DIR / "distances"
GU_DIST_PATH = DISTANCES_DIR / "gu_node2vec_cosine.npy"
GY_DIST_PATH = DISTANCES_DIR / "gy_node2vec_cosine.npy"

# --- Output: results and plots ---
RESULTS_DIR = Path("results")
PLOTS_DIR = Path("plots")
